# ==============================
# 1. BASE IMAGE
# ==============================
FROM php:8.2-apache

# ==============================
# 2. INSTALL MYSQL EXTENSION
# ==============================
RUN docker-php-ext-install mysqli

# ==============================
# 3. COPY FRONTEND FILES
# ==============================
COPY ../frontend/ /var/www/html/

# ==============================
# 4. COPY BACKEND FILES
# ==============================
COPY . /var/www/html/

# ==============================
# 5. SET PERMISSIONS
# ==============================
RUN chown -R www-data:www-data /var/www/html