apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-app
  template:
    metadata:
      labels:
        app: ticket-app
    spec:
      containers:
      - name: ticket-app
        image: ticket-backend:v4
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "mysql-service" # This is the magic! No more IPs.
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: password
        - name: DB_NAME
          value: "tickets"
...
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: ticket-app
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30007 # This is the 'Public Door' (Range: 30000-32767)
  type: NodePort
