pipeline {
    agent any 

    environment {
        IMAGE_NAME = "ticket-app"
    }

    stages {
        stage('Checkout') {
            steps {
                echo '--- Fetching Code from GitHub ---'
                checkout scm
            }
        }

        stage('Validation') {
            steps {
                echo '--- Running Code Validation ---'
                sh 'ls -R app/ && echo "Structure Verified"'
            }
        }

        stage('Build Image') {
            steps {
                echo '--- Building Docker Image Locally ---'
                // Update the path after -f to where your file actually is
                sh "docker build -t ${IMAGE_NAME}:latest -f docker/Dockerfile ."
                
                echo '--- Loading Image into Minikube ---'
                sh "minikube image load ${IMAGE_NAME}:latest --overwrite"
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo '--- Applying Kubernetes Manifests ---'
                sh "kubectl apply -f k8s/namespace.yaml"
                sh "kubectl apply -f k8s/configmap.yaml"
                sh "kubectl apply -f k8s/deployment.yaml"
                sh "kubectl apply -f k8s/service.yaml"
                
                echo '--- Forcing Pod Refresh ---'
                sh "kubectl rollout restart deployment/ticket-app -n ticket-app-ns"
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}