pipeline {
    agent any 

    environment {
        IMAGE_NAME = "ticket-app"
    }

    stages {
        stage('Checkout') {
            steps {
                echo '--- Fetching Code from GitHub ---'
                checkout scm
            }
        }

        stage('Validation') {
            steps {
                echo '--- Running Code Validation ---'
                sh 'ls -R app/ && echo "Structure Verified"'
            }
        }

        stage('Build Image') {
    steps {
        // Move up one level to the root before building
        dir('..') { 
            echo '--- Building Docker Image from Root ---'
            sh "docker build --no-cache -t ${IMAGE_NAME}:latest -f docker/Dockerfile ."
            sh "minikube image load ${IMAGE_NAME}:latest --overwrite"
        }
    }
}

        stage('Deploy to Kubernetes') {
    steps {
        echo '--- Applying Kubernetes Manifests ---'
        // Apply changes to namespace, config, etc.
        sh "kubectl apply -f k8s/namespace.yaml"
        sh "kubectl apply -f k8s/deployment.yaml"
        sh "kubectl apply -f k8s/service.yaml"
        
        echo '--- Forcing Pod Refresh ---'
        // This command forces K8s to pull the new 'latest' image
        sh "kubectl rollout restart deployment/ticket-app -n ticket-app-ns"
        
        // This makes Jenkins wait until the new version is actually live
        sh "kubectl rollout status deployment/ticket-app -n ticket-app-ns"
         }
    }
}

    post {
        always {
            cleanWs()
        }
    }
}