apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-app
  namespace: ticket-app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-app
  template:
    metadata:
      labels:
        app: ticket-app
    spec:
      containers:
      - name: ticket-web
        # MATCHED: This now matches the IMAGE_NAME in your Jenkinsfile
        image: ticket-app:latest  
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: DB_PASS
          value: "password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: ticket-app-ns
spec:
  selector:
    matchLabels:
      app: ticket-db
  template:
    metadata:
      labels:
        app: ticket-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "ticket_db"