name: TicketApp-Auto-Deploy
# 1. When should this run? (Every time we push to the 'main' branch)
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 2. Tell GitHub to log into our EC2 using the secrets we saved
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 3. These are the commands that run ON your EC2
            cd ~/Ticket-App
            git pull origin main
            
            # Use Minikube's internal Docker to build the new image
            eval $(minikube docker-env)
            docker build -t ticket-backend:v4 -f Backend/Dockerfile .
            
            # Tell Kubernetes to throw away the old Pod and start a new one with the new code
            kubectl rollout restart deployment ticket-app
